services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: xxx
      POSTGRES_PASSWORD: xxx
      POSTGRES_DB: lummytopup
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xxx -d lummytopup"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    restart: always
    env_file:
      - ./backend/.prod.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    restart: always
    env_file:
      - ./frontend/.prod.env

  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run --token xx
    depends_on:
      - api_gateway

volumes:
  postgres_data:
